---
- name: Join Kubernetes Worker Nodes
  hosts: kube_workers
  become: true
  tasks:
    - name: Get join command from master
      ansible.builtin.command: kubeadm token create --print-join-command
      delegate_to: master_node
      run_once: true
      register: join_command_output

    - name: Store join command in a local variable
      ansible.builtin.set_fact:
        kube_join_command: "{{ join_command_output.stdout }}"

    - name: Join worker node to cluster
      ansible.builtin.command: "{{ kube_join_command }}"
      args:
        creates: /etc/kubernetes/kubelet.conf # Prevent re-running if already joined
